/* traduction en locale fr */
PrimeFaces.locales ['fr'] = {
		closeText: 'Fermer',
		prevText: 'Pr\u00E9c\u00E9dent',
		nextText: 'Suivant',
		monthNames: ['Janvier', 'F\u00E9vrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Ao\u00FBt', 'Septembre', 'Octobre', 'Novembre', 'D\u00E9cembre' ],
		monthNamesShort: ['Jan', 'F\u00E9v', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Ao\u00FB', 'Sep', 'Oct', 'Nov', 'D\u00E9c' ],
		dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
		dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
		dayNamesMin: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa'],
		weekHeader: 'Semaine',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix:'',
		timeOnlyTitle: 'Choisir l\'heure',
		timeText: 'Heure',
		hourText: 'Heures',
		minuteText: 'Minutes',
		secondText: 'Secondes',
		currentText: 'Maintenant',
		ampm: false,
		month: 'Mois',
		week: 'Semaine',
		day: 'Jour',
		allDayText: 'Toute la journ\u00E9e'
	};
